### ISSUE TITLE
7z error

### ISSUE THREAD

**Issue by Y-A-K-E** [mgrinzPlayer/CheatEngineUpDeluxe#1]
hello,

7za cannot unzip.

FPC 3.2.0, branch: fixes_3_2, revision 42444
Lazarus 2.0.0, tag: lazarus_2_0_0, revision 60307

Download FPC from [o]fficial source or [c]ompressed source or
[r]eady to use Compiled 32bit FPC with crosscompiler[o,c,r]?c

Download Lazarus from [o]fficial source or [c]ompressed source [o,c]?c

Do you want [t]32 or [s]64 bit environment [t,s]?s

Do you want crosscompiler [y,n]?y

Downloading FPC: 100%
Extracting FPC...
Downloading Lazarus: 100%
Extracting Lazarus...
Downloading bootstrap: 100%
Extracting bootstrap...

ERROR: 系统找不到指定的文件。 (English:The system cannot find the specified file)
bootstrap.7z

System ERROR:
系统找不到指定的文件。  (English:The system cannot find the specified file)
Downloading GDB: 100%
64bit FPC - all install
crosscompiler - compiler
crosscompiler - rtl
crosscompiler - packages
cleaning
creating clean source
系统找不到指定的路径。  (English:The system cannot find the specified file)
'"C:\Windows\system32\fpc\3.2.0\bin\x86_64-win64\fpcmkcfg.exe"' 不是内部或外部命令，也不是可运行的程序或批处理文件。 (English:is not an internal or external command, nor is it a runnable program or batch file)
系统找不到指定的路径。  (English:The system cannot find the specified file)
系统找不到指定的路径。  (English:The system cannot find the specified file)
Compiling Lazbuild
Compiling registration lazutils lcl basecomponents
Compiling starter
Compiling Lazarus

Extracting GDB...

ERROR: 系统找不到指定的文件。  (English:The system cannot find the specified file)
..\mingw.7z

---------------------------------

C:\Windows\system32>dir |findstr "7z"
2019/10/15  14:00           739,840 7za.exe
2019/10/15  14:29         3,960,003 bootstrap.7z
2019/10/15  15:03        23,838,964 fpcsrc.7z
2019/10/15  15:05        20,427,343 lazarus.7z
2019/10/15  14:29         3,032,942 mingw.7z

**Comment by mgrinzPlayer** [comment]
>C:\Windows\system32>dir |findstr "7z"

You placed "prepare Lazarus Env.cmd" file inside C:\Windows\system32 folder?

Create folder on any partition where you have write permission and move cmd file there.
For example:
C:\LazarusForCheatEngine70\

Also make sure there are no spaces and non-english characters in the path.
Lazarus and FPC don't like those. It was a problem in the past, I don't know they fixed it or not.

**Comment by Y-A-K-E** [comment]
I download your project in GitHub,I unzip the file to the desktop, 
as administrator runs "prepare Lazarus Env.cmd".

It downloads the files to the system32 folder.

-----------
C:\Users\xjw11\Desktop\CheatEngineUpDeluxe-master>dir


2019/09/23  20:42    <DIR>          .
2019/09/23  20:42    <DIR>          ..
2019/09/23  20:42         3,960,003 bootstrap.7z
2019/10/15  16:06    <DIR>          compiledFPC
2019/09/23  20:42        23,838,964 fpcsrc.7z
2019/09/23  20:42        20,427,343 lazarus.7z
2019/09/23  20:42         3,032,942 mingw.7z
2019/09/23  20:42             2,398 prepare CE.cmd
2019/10/15  15:25            11,949 prepare Lazarus Env.cmd
2019/09/23  20:42             1,220 README.md
2019/09/23  20:42             7,963 screenshot.png
2019/09/23  20:42    <DIR>          tool
               8 个文件     51,282,782 字节
               4 个目录 138,975,776,768 可用字节

**Comment by mgrinzPlayer** [comment]
do not download whole repository, just cmd file.

add  this at the beginning of "prepare Lazarus Env.cmd" file
`cd /d "%~dp0"`

**Comment by Y-A-K-E** [comment]
yes,it's work. thanks!
